import sys

env = Environment()

MyFlags = env['CCFLAGS']
MyFlags.append('--std=c++14')
if sys.platform == 'win32':
    MyFlags.append( '/EHsc')

Program("balanced_tree.cpp", CCFLAGS=MyFlags)
#Program("find_path.cpp", CCFLAGS=MyFlags)
Program("is_bst.cpp", CCFLAGS=MyFlags)
Program("depth_list.cpp", CCFLAGS=MyFlags)
Program("build_tree.cpp", CCFLAGS=MyFlags)

