import sys

env = Environment()

MyFlags = env['CCFLAGS']
MyFlags.append('--std=c++14')
if sys.platform == 'win32':
    MyFlags.append( '/EHsc')

Program("test_list.cpp", CCFLAGS=MyFlags)
Program("find_duplicate.cpp", CCFLAGS=MyFlags)
Program("k_to_last.cpp", CCFLAGS=MyFlags)
