import sys

env = Environment()

MyFlags = env['CCFLAGS']
MyFlags.append('--std=c++14')
if sys.platform == 'win32':
    MyFlags.append( '/EHsc')

Program("3stacks.cpp", CCFLAGS=MyFlags)
Program("min_stack.cpp", CCFLAGS=MyFlags)
Program("queue_stack.cpp", CCFLAGS=MyFlags)
