import sys

env = Environment()

MyFlags = env['CCFLAGS']
MyFlags.append('--std=c++17')
if sys.platform == 'win32':
    MyFlags.append( '/EHsc')

Program("stair_steps.cpp", CCFLAGS=MyFlags)
Program("robot_ways_2dgrid.cpp", CCFLAGS=MyFlags)
Program("all_subsets.cpp", CCFLAGS=MyFlags)
Program("all_strings.cpp", CCFLAGS=MyFlags)
Program("match_paren.cpp", CCFLAGS=MyFlags)
Program("paint_fill.cpp", CCFLAGS=MyFlags)
