import sys

env = Environment()

MyFlags = env['CCFLAGS']
MyFlags.append('--std=c++14')
if sys.platform == 'win32':
    MyFlags.append( '/EHsc')

Program("stair_steps.cpp", CCFLAGS=MyFlags)
Program("all_subsets.cpp", CCFLAGS=MyFlags)
